<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'modules\\' => array($baseDir . '/modules'),
    'jamesiarmes\\PhpNtlm\\' => array($vendorDir . '/jamesiarmes/php-ntlm/src'),
    'jamesiarmes\\PhpEws\\' => array($vendorDir . '/php-ews/php-ews/src'),
    'Wsdl2PhpGenerator\\' => array($vendorDir . '/wsdl2phpgenerator/wsdl2phpgenerator/src', $vendorDir . '/wsdl2phpgenerator/wsdl2phpgenerator/lib'),
    'Twig\\' => array($vendorDir . '/twig/twig/src'),
    'TelegramBot\\Api\\' => array($vendorDir . '/telegram-bot/api/src'),
    'Symfony\\Polyfill\\Iconv\\' => array($vendorDir . '/symfony/polyfill-iconv'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\OptionsResolver\\' => array($vendorDir . '/symfony/options-resolver'),
    'Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'Symfony\\Component\\DependencyInjection\\' => array($vendorDir . '/symfony/dependency-injection'),
    'Symfony\\Component\\Config\\' => array($vendorDir . '/symfony/config'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'PhantomInstaller\\Test\\' => array($vendorDir . '/jakoch/phantomjs-installer/tests'),
    'Botb\\' => array($baseDir . '/core'),
    'BotbLib\\' => array($baseDir . '/lib'),
    '' => array($vendorDir . '/ambalus/dbsimple/src'),
);
